import "./globals.css";
import { Header } from "@/app/components/header";
import { CustomScrollbar } from "@/app/components/scrollbar";
import { Footer } from "@/app/components/footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "STEMXIO: Next Generation STEM Education",
  description: "Generated by create next app",
  openGraph: {
    title: "STEMXIO: Next Generation STEM Education",
    description:
      "Empowering the next generation of innovators through cutting-edge STEM education",
    url: "https://stemxio.com",
    siteName: "STEMXIO",
    images: [
      {
        url: "https://stemxio.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "STEMXIO",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "STEMXIO: Next Generation STEM Education",
    description:
      "Empowering the next generation of innovators through cutting-edge STEM education",
    images: ["https://stemxio.com/og-image.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col bg-black`}
      >
        <CustomScrollbar />
        <header className="fixed top-0 w-full z-50">
          <Header />
        </header>
        <main className="flex-1 w-full pt-24">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
